/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateAnswerResponseSelectedDocumentsInner } from '../models/CreateAnswerResponseSelectedDocumentsInner.js';
import { HttpFile } from '../http/http.js';

export class CreateAnswerResponse {
    'object'?: string;
    'model'?: string;
    'search_model'?: string;
    'completion'?: string;
    'answers'?: Array<string>;
    'selected_documents'?: Array<CreateAnswerResponseSelectedDocumentsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "searchModel",
            "baseName": "search_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "completion",
            "baseName": "completion",
            "type": "string",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "selectedDocuments",
            "baseName": "selected_documents",
            "type": "Array<CreateAnswerResponseSelectedDocumentsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAnswerResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

