/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class CreateModerationResponseResultsInnerCategories {
    'hate': boolean;
    'hate/threatening': boolean;
    'self-harm': boolean;
    'sexual': boolean;
    'sexual/minors': boolean;
    'violence': boolean;
    'violence/graphic': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hate",
            "baseName": "hate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hateThreatening",
            "baseName": "hate/threatening",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "selfHarm",
            "baseName": "self-harm",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sexual",
            "baseName": "sexual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sexualMinors",
            "baseName": "sexual/minors",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "violence",
            "baseName": "violence",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "violenceGraphic",
            "baseName": "violence/graphic",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateModerationResponseResultsInnerCategories.attributeTypeMap;
    }

    public constructor() {
    }
}

