/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class CreateImageRequest {
    /**
    * A text description of the desired image(s). The maximum length is 1000 characters.
    */
    'prompt': string;
    /**
    * The number of images to generate. Must be between 1 and 10.
    */
    'n'?: number;
    /**
    * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
    */
    'size'?: CreateImageRequestSizeEnum;
    /**
    * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
    */
    'response_format'?: CreateImageRequestResponseFormatEnum;
    /**
    * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). 
    */
    'user'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string",
            "format": ""
        },
        {
            "name": "n",
            "baseName": "n",
            "type": "number",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "CreateImageRequestSizeEnum",
            "format": ""
        },
        {
            "name": "responseFormat",
            "baseName": "response_format",
            "type": "CreateImageRequestResponseFormatEnum",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateImageRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateImageRequestSizeEnum = "256x256" | "512x512" | "1024x1024" ;
export type CreateImageRequestResponseFormatEnum = "url" | "b64_json" ;

