/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateCompletionResponseChoicesInnerLogprobs } from '../models/CreateCompletionResponseChoicesInnerLogprobs.js';
import { HttpFile } from '../http/http.js';

export class CreateCompletionResponseChoicesInner {
    'text'?: string;
    'index'?: number;
    'logprobs'?: CreateCompletionResponseChoicesInnerLogprobs;
    'finish_reason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "logprobs",
            "baseName": "logprobs",
            "type": "CreateCompletionResponseChoicesInnerLogprobs",
            "format": ""
        },
        {
            "name": "finishReason",
            "baseName": "finish_reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCompletionResponseChoicesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

