/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class CreateEmbeddingResponseDataInner {
    'index': number;
    'object': string;
    'embedding': Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "embedding",
            "baseName": "embedding",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateEmbeddingResponseDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

