/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateModerationResponseResultsInnerCategories } from '../models/CreateModerationResponseResultsInnerCategories.js';
import { CreateModerationResponseResultsInnerCategoryScores } from '../models/CreateModerationResponseResultsInnerCategoryScores.js';
import { HttpFile } from '../http/http.js';

export class CreateModerationResponseResultsInner {
    'flagged': boolean;
    'categories': CreateModerationResponseResultsInnerCategories;
    'category_scores': CreateModerationResponseResultsInnerCategoryScores;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "flagged",
            "baseName": "flagged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "CreateModerationResponseResultsInnerCategories",
            "format": ""
        },
        {
            "name": "categoryScores",
            "baseName": "category_scores",
            "type": "CreateModerationResponseResultsInnerCategoryScores",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateModerationResponseResultsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

