/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FineTuneEvent } from '../models/FineTuneEvent.js';
import { OpenAIFile } from '../models/OpenAIFile.js';
import { HttpFile } from '../http/http.js';

export class FineTune {
    'id': string;
    'object': string;
    'created_at': number;
    'updated_at': number;
    'model': string;
    'fine_tuned_model': string;
    'organization_id': string;
    'status': string;
    'hyperparams': any;
    'training_files': Array<OpenAIFile>;
    'validation_files': Array<OpenAIFile>;
    'result_files': Array<OpenAIFile>;
    'events'?: Array<FineTuneEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "fineTunedModel",
            "baseName": "fine_tuned_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "hyperparams",
            "baseName": "hyperparams",
            "type": "any",
            "format": ""
        },
        {
            "name": "trainingFiles",
            "baseName": "training_files",
            "type": "Array<OpenAIFile>",
            "format": ""
        },
        {
            "name": "validationFiles",
            "baseName": "validation_files",
            "type": "Array<OpenAIFile>",
            "format": ""
        },
        {
            "name": "resultFiles",
            "baseName": "result_files",
            "type": "Array<OpenAIFile>",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<FineTuneEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FineTune.attributeTypeMap;
    }

    public constructor() {
    }
}

