/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class ImagesResponseDataInner {
    'url'?: string;
    'b64_json'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "b64Json",
            "baseName": "b64_json",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImagesResponseDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

